api_key: 'a0ae25cdc62039bb6ccfd88cd911739a'
domain: 'sandboxfedbdf32897a4ea69d1f343bdbc71e20.mailgun.org'
username: 'jpbamberg1993@gmail.com'
password: 'logistic'
gmail_username: 'johnpaulprince22@gmail.com'
gmail_password: 'logistics'
